CosmWasm/sylvia

Cargo.lock
Cargo.toml
contracts/cw1-whitelist/Cargo.toml
contracts/cw1-whitelist/src/contract.rs
contracts/cw1-whitelist/src/error.rs
contracts/cw1-whitelist/src/lib.rs
contracts/cw1-whitelist/src/multitest.rs
contracts/cw1/src/lib.rs

Coverage of Cw1Whitelist in sylvia.

Cw1 whitelist

---

.github/workflows/ci.yml
contracts/cw1-whitelist/Cargo.toml
sylvia-derive/src/message.rs

Allow derive partial eq without eq and CI coverage

---

CHANGELOG.md

Added description of 0.2 release.

Created changelog file.

---

Cargo.lock
contracts/cw1-subkeys/Cargo.toml
contracts/cw1-subkeys/src/contract.rs
contracts/cw1-subkeys/src/responses.rs
contracts/cw1-subkeys/src/state.rs
contracts/cw1-whitelist/Cargo.toml
contracts/cw1-whitelist/src/contract.rs
contracts/cw1-whitelist/src/responses.rs
contracts/cw1-whitelist/src/whitelist.rs
contracts/cw1/Cargo.toml
contracts/cw1/src/lib.rs
contracts/cw4/Cargo.toml
contracts/cw4/src/lib.rs
sylvia-derive/src/message.rs
sylvia/Cargo.toml

Remove schemars dependency from contracts.

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.lock
contracts/cw20-allowances/src/lib.rs
contracts/cw20-allowances/src/responses.rs
contracts/cw20-base/.cargo/config
contracts/cw20-base/Cargo.toml
contracts/cw20-base/src/allowances.rs
contracts/cw20-base/src/bin/schema.rs
contracts/cw20-base/src/contract.rs
contracts/cw20-base/src/lib.rs
contracts/cw20-base/src/marketing.rs
contracts/cw20-base/src/minting.rs
contracts/cw20-base/src/multitest.rs
contracts/cw20-base/src/multitest/allowances_tests.rs
contracts/cw20-base/src/multitest/base_tests.rs
contracts/cw20-base/src/multitest/marketing_tests.rs
contracts/cw20-base/src/multitest/minting_tests.rs
contracts/cw20-base/src/multitest/proxy.rs
contracts/cw20-marketing/src/lib.rs
contracts/cw20-minting/src/lib.rs

Cw20 port in sylvia

---

CHANGELOG.md
Cargo.lock
contracts/cw1-subkeys/Cargo.toml
contracts/cw1-whitelist/Cargo.toml
contracts/cw20-base/Cargo.toml
interfaces/cw1/Cargo.toml
interfaces/cw20-allowances/Cargo.toml
interfaces/cw20-marketing/Cargo.toml
interfaces/cw20-minting/Cargo.toml
interfaces/cw4/Cargo.toml
sylvia-derive/Cargo.toml
sylvia-derive/src/message.rs
sylvia/Cargo.toml
sylvia/src/lib.rs

Better error messages

---

sylvia-derive/src/input.rs
sylvia-derive/src/message.rs
sylvia-derive/src/strip_input.rs
sylvia/tests/messages_generation.rs
sylvia/tests/query_returns.rs

Forward fields attrs

---

sylvia/src/into_deps.rs
sylvia/src/lib.rs

Deps conversion

---

Cargo.lock
README.md
sylvia-derive/src/input.rs
sylvia-derive/src/parser.rs
sylvia-derive/src/strip_input.rs
sylvia/tests/custom_msg.rs

Custom attr

---

.github/workflows/ci.yml
MIGRATING.md
sylvia/src/types.rs

Replace context aliases

---

sylvia-derive/src/input.rs
sylvia-derive/src/message.rs
sylvia-derive/src/multitest.rs
sylvia-derive/src/parser.rs
sylvia/tests/entry_points.rs

feat: Override entry_points in multitest helpers

---

sylvia-derive/src/input.rs
sylvia-derive/src/message.rs
sylvia-derive/src/multitest.rs
sylvia-derive/src/parser.rs
sylvia/tests/custom_msg.rs
sylvia/tests/custom_query.rs
sylvia/tests/messages_generation.rs

feat: Support custom queries on contracts

---

.github/workflows/ci.yml
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
examples/contracts/entry-points-overriding/.cargo/config
examples/contracts/entry-points-overriding/Cargo.toml
examples/contracts/entry-points-overriding/src/bin/schema.rs
examples/contracts/entry-points-overriding/src/contract.rs
examples/contracts/entry-points-overriding/src/entry_points.rs
examples/contracts/entry-points-overriding/src/lib.rs
examples/contracts/entry-points-overriding/src/messages.rs
examples/contracts/entry-points-overriding/src/multitest.rs
sylvia-derive/src/input.rs
sylvia-derive/src/message.rs
sylvia-derive/src/multitest.rs
sylvia-derive/src/parser.rs
sylvia/src/types.rs
sylvia/tests/entry_points.rs

feat: Entry points overriding

---

sylvia-derive/src/message.rs
sylvia-derive/src/multitest.rs
sylvia-derive/src/parser.rs
sylvia/tests/custom_query.rs

feat: Support QueryC associated type on interface

---

sylvia-derive/src/message.rs
sylvia/tests/dispatching.rs
sylvia/tests/entry_points.rs
sylvia/tests/messages_generation.rs

Sudo entry point

---

examples/contracts/custom/src/contract.rs
examples/contracts/custom/src/multitest/tests.rs
sylvia-derive/src/message.rs

test: Add sudo to custom example

---

README.md
examples/contracts/custom/src/multitest/tests.rs
examples/contracts/cw1-subkeys/src/multitest/tests.rs
examples/contracts/cw1-whitelist/src/multitest.rs
examples/contracts/cw20-base/src/multitest/allowances_tests.rs
examples/contracts/cw20-base/src/multitest/base_tests.rs
examples/contracts/cw20-base/src/multitest/marketing_tests.rs
examples/contracts/cw20-base/src/multitest/minting_tests.rs
examples/contracts/entry-points-overriding/src/multitest.rs
examples/contracts/generic_contract/src/contract.rs
examples/contracts/generic_contract/src/custom_and_generic.rs
examples/contracts/generic_contract/src/cw1.rs
examples/contracts/generic_contract/src/generic.rs
examples/contracts/generic_iface_on_contract/src/contract.rs
examples/contracts/generics_forwarded/src/contract.rs
examples/contracts/generics_forwarded/src/custom_and_generic.rs
examples/contracts/generics_forwarded/src/cw1.rs
examples/contracts/generics_forwarded/src/generic.rs
sylvia-derive/src/multitest.rs
sylvia/tests/custom_msg.rs
sylvia/tests/custom_query.rs
sylvia/tests/entry_points.rs
sylvia/tests/multitest.rs
sylvia/tests/querier.rs
sylvia/tests/replies.rs

feat: Change multitest modules names to unified `mt` (#324)

---

examples/contracts/cw1-subkeys/src/multitest/tests.rs
sylvia-derive/src/message.rs
sylvia-derive/src/multitest.rs
sylvia/src/multitest.rs

feat: Implement Querier on App (#154)

---

examples/contracts/cw1-subkeys/Cargo.toml
examples/contracts/cw1-whitelist/Cargo.toml
examples/contracts/cw1-whitelist/src/lib.rs
examples/contracts/cw20-base/Cargo.toml
examples/contracts/entry-points-overriding/Cargo.toml
examples/contracts/generic_contract/Cargo.toml
examples/contracts/generic_iface_on_contract/Cargo.toml
examples/contracts/generics_forwarded/Cargo.toml

chore: Unify feature names in examples (#175)

---

sylvia-derive/src/parser/attributes/custom.rs
sylvia/tests/ui/attributes/custom/invalid_custom.rs
sylvia/tests/ui/attributes/custom/invalid_custom.stderr

chore: Improve error message in `sv::custom` attribute (#348)

---

sylvia-derive/src/message.rs
sylvia-derive/src/multitest.rs

Cleanup in `Multitest` generation. After removing the support for the `contract` macro on `impl Interface` we can merge some methods as they do not differ this much between `interface` and `contract`.

chore: Unify MT proxy methods emit

---

sylvia-derive/src/message.rs
sylvia-derive/src/message_type.rs
sylvia-derive/src/multitest.rs
sylvia-derive/src/querier.rs
sylvia-derive/src/utils.rs

chore: Provide `to_case` functionality to `syn::Ident`

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
examples/contracts/cw1-whitelist/src/contract.rs
sylvia-derive/src/parser/attributes/messages.rs
sylvia/Cargo.toml
sylvia/src/multitest.rs
sylvia/tests/dispatching.rs

Wait for `cw_multi_test 2.1.0` to be released before merging.

chore: Update dependecies

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
examples/contracts/custom/src/multitest/custom_module.rs
sylvia/Cargo.toml
sylvia/src/types.rs
sylvia/tests/reply_data.rs
sylvia/tests/ui/macros/entry_points.stderr

- Upgraded `cosmwasm-std` dependency to version **3.0.0-rc.0**.
- Upgraded other required dependencies.

Upgraded cosmwasm-std to version 3.0.0-rc.0
